theme: jekyll-theme-minimal
title: Collab 19
description: A DAO to fight COV-19
logo: help.png

How can you help?

[Join the DAO](https://t.me/collab19_bot) to help decide which charities to donate to!
[Donate DAI!}(0x66b6FD8097e078CB8E0F7916efB8Be76849B3442)
